#######################
# Names and constants #
#######################
hu_mapping_dict_countynames = {
    'BACS'      :   'Bacs Kiskun', 
    'BARANYA'   :   'Baranya', 
    'BEKES'     :   'Bekes', 
    'BORSOD'    :   'Borsod Abauj Zemplen', 
    'BUDAPEST'  :   'Budapest', 
    'CSONGRAD'  :   'Csongrad',
    'FEJER'     :   'Fejer', 
    'GYOR'      :   'Gyor Moson Sopron', 
    'HAJDU'     :   'Hajdu Bihar', 
    'HEVES'     :   'Heves', 
    'JASZ'      :   'Jasz Nagykun Szolnok', 
    'KOMAROM'   :   'Komarom Esztergom', 
    'NOGRAD'    :   'Nograd',
    'PEST'      :   'Pest megye', 
    'SOMOGY'    :   'Somogy', 
    'SZABOLCS'  :   'Szabolcs Szatmar Bereg', 
    'TOLNA'     :   'Tolna', 
    'VAS'       :   'Vas', 
    'VESZPREM'  :   'Veszprem', 
    'ZALA'      :   'Zala'
}
hu_counties                 = list(hu_mapping_dict_countynames.values())
n_counties                  = 20

hu_countynames_tokens = {'Bacs Kiskun': 0,
 'Baranya': 1,
 'Bekes': 2,
 'Borsod Abauj Zemplen': 3,
 'Budapest': 4,
 'Csongrad': 5,
 'Fejer': 6,
 'Gyor Moson Sopron': 7,
 'Hajdu Bihar': 8,
 'Heves': 9,
 'Jasz Nagykun Szolnok': 10,
 'Komarom Esztergom': 11,
 'Nograd': 12,
 'Pest megye': 13,
 'Somogy': 14,
 'Szabolcs Szatmar Bereg': 15,
 'Tolna': 16,
 'Vas': 17,
 'Veszprem': 18,
 'Zala': 19}

hu_tokens_countynames = {0: 'Bacs Kiskun',
 1: 'Baranya',
 2: 'Bekes',
 3: 'Borsod Abauj Zemplen',
 4: 'Budapest',
 5: 'Csongrad',
 6: 'Fejer',
 7: 'Gyor Moson Sopron',
 8: 'Hajdu Bihar',
 9: 'Heves',
 10: 'Jasz Nagykun Szolnok',
 11: 'Komarom Esztergom',
 12: 'Nograd',
 13: 'Pest megye',
 14: 'Somogy',
 15: 'Szabolcs Szatmar Bereg',
 16: 'Tolna',
 17: 'Vas',
 18: 'Veszprem',
 19: 'Zala'}