map_iata_colnames={'Travel Month'           : 'month', 
                  'Travel Year'             : 'year', 
                  'Trip Orig Country Desc'  : 'ori_cntry',  
                  'Trip Dest Country Desc'  : 'dest_cntry', 
                  'Pax Count'               : 'passengers'}

map_popsize_data_countrynames = {
'American Samoa'                : 'Samoa',
'Bahamas, The'                  : 'Bahamas',
'Congo, Rep.'                   : 'Congo',
'Congo, Dem. Rep.'              : 'Democratic Republic of the Congo',
'Egypt, Arab Rep.'              : 'Egypt',
'Gambia, The'                   : 'Gambia',
'Iran, Islamic Rep.'            : 'Iran',
'Kyrgyz Republic'               : 'Kyrgyzstan',
'Lao PDR'                       : "Laos",
'Micronesia, Fed. Sts.'         : 'Micronesia',
"Korea, Dem. People's Rep."     : 'North Korea',
'Korea, Rep.'                   : 'South Korea',
'St. Kitts and Nevis'           : 'Saint Kitts and Nevis',
'St. Lucia'                     : "Saint Lucia",
'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
'Slovak Republic'               : 'Slovakia',
'Venezuela, RB'                 : 'Venezuela',
'Yemen, Rep.'                   : 'Yemen',
'Syrian Arab Republic'          : "Syria",
'United States'                 : "United States of America",
"Viet Nam"                      : "Vietnam"
}

map_popsize_data_additional_countrynames = {
    'Aruba'                         :   'Netherlands',
    'Bermuda'                       :   'United Kingdom',
    'Channel Islands'               :   'United Kingdom',
    'Curacao'                       :   'Netherlands',
    'Cayman Islands'                :   "United Kingdom",
    'Faroe Islands'                 :   'Denmark',
    'Gibraltar'                     :   'United Kingdom',
    'Greenland'                     :   'Denmark',
    'Guam'                          :   'United States of America',
    'Hong Kong SAR, China'          :   'China',
    'Isle of Man'                   :   'United Kingdom',
    'Macao SAR, China'              :   'China',
    'St. Martin (French part)'      :   'France',
    'Northern Mariana Islands'      :   'United States of America',
    'New Caledonia'                 :   'France',
    'Puerto Rico'                   :   'United States of America',
    'West Bank and Gaza'            :   'Palestinian Territories',
    'French Polynesia'              :   'France',
    'Sint Maarten (Dutch part)'     :   'Netherlands',
    'Turks and Caicos Islands'      :   'United Kingdom',
    'British Virgin Islands'        :   'United Kingdom',
    'Virgin Islands (U.S.)'         :   'United States of America',
    'Kosovo'                        :   'Serbia'
    }

map_who_vaxdata_countrynames = {
'Bolivia (Plurinational State of)'                      : 'Bolivia',
"Côte d'Ivoire"                                         : "Cote d'Ivoire",
'Nuie'                                                  : "New Zealand",
'Iran (Islamic Republic of)'                            : 'Iran',
'Micronesia (Federated States of)'                      : 'Micronesia',
'Netherlands (Kingdom of the)'                          : 'Netherlands',
'Republic of Moldova'                                   : 'Moldova',
'Republic of Korea'                                     : 'South Korea',
'United Republic of Tanzania'                           : 'Tanzania',
'Türkiye'                                               : 'Turkiye',
'United Kingdom of Great Britain and Northern Ireland'  : 'United Kingdom',
'Venezuela (Bolivarian Republic of)'                    : 'Venezuela',
"Democratic People's Republic of Korea"                 : 'North Korea',
"Lao People's Democratic Republic"                      : 'Laos',
'Syrian Arab Republic'                                  : "Syria",
"Viet Nam"                                              :"Vietnam",
'occupied Palestinian territory, including east Jerusalem': 'Palestinian Territories'
}

map_naturalearth_countrynames = {
'Brunei'                        : 'Brunei Darussalam',
'Republic of the Congo'         : 'Congo',
'Ivory Coast'                   : "Cote d'Ivoire",
'Federated States of Micronesia': 'Micronesia',
'Russia'                        : 'Russian Federation',
'eSwatini'                      : 'Eswatini',
'Republic of Serbia'            : 'Serbia',
"United Republic of Tanzania"   : "Tanzania",
"The Bahamas"                   : "Bahamas",
"São Tomé and Principe"         : "Sao Tome and Principe",
"East Timor"                    : "Timor-Leste",
"Turkey"                        : "Turkiye",
'Palestine'                     : 'Palestinian Territories',
}

map_iata_countrynames = {
 'Russian Fed.'         :   'Russian Federation',
 'USA'                  :   'United States of America',
 'Türkiye'              :   'Turkiye',
 'Congo  Democra'       :   'Democratic Republic of the Congo',
 'CAR'                  :   'Central African Republic',
 'Viet Nam'             :   'Vietnam',
 'Bosnia-Herz.'         :   'Bosnia and Herzegovina',
 'Equatorial Guin'      :   'Equatorial Guinea',
 'Cape Verde'           :   'Cabo Verde',
 'Brunei Daruss.'       :   'Brunei Darussalam',
 'French Guayana'       :   'Guinea',
 'Macedonia'            :   'North Macedonia',
 'Mauretania'           :   'Mauritania',
 'Reunion'              :   'France',
 'Dominican Rep.'       :   'Dominican Republic',
 'Marshall Islnds'      :   'Marshall Islands',
 'Pap. New Guinea'      :   'Papua New Guinea',
 'St. Vincent'          :   'Saint Vincent and the Grenadines',
 'Antigua/Barbuda'      :   'Antigua and Barbuda',
 'St Kitts&Nevis'       :   'Saint Kitts and Nevis',
 'St. Lucia'            :   'Saint Lucia',
 'S.TomePrincipe'       :   'Sao Tome and Principe',
 'TrinidadTobago'       :   'Trinidad and Tobago',
 'Utd.Arab Emir.'       :   'United Arab Emirates',     
 'Frenc.Polynesia'      :   'French Polynesia'                                                                                                            # Not fair! near Madagascar
}

map_iata_additional_countrynames = {
    "French Polynesia"          :   "France",
    "Guernsey"                  :   "United Kingdom",
    "Greenland"                 :   "Denmark",
    "Cook Islands"              :   "New Zealand",
    "Aruba"                     :   "Netherlands",
    "Anguilla"                  :   "United Kingdom",
    "Bermuda"                   :   "United Kingdom",
    "New Caledonia"             :   "France",
    "Bonaire"                   :   "Netherlands",
    "Puerto Rico"               :   "United States of America",
    "Cocos Islands"             :   "Australia",
    "Curacao"                   :   "Netherlands",
    "Cayman Islands"            :   "United Kingdom",
    "Chinese Taipei"            :   "China",
    "Mayotte"                   :   "France",
    'Brit.Virgin Is.'           :   "United Kingdom",
    'Faroe Islands'             :   "Denmark",
    'Martinique'                :   "France",
    'St.PierMiquel.'            :   "France",
    'WallisFutuna'              :   "France",     
    'Turksh Caicosin'           :   "United Kingdom",
    'Gibraltar'                 :   "United Kingdom",
    'Guam'                      :   "United States of America",
    'Hong Kong'                 :   "China",
    'Isle of Man'               :   "United Kingdom",  
    'Niue'                      :   "New Zealand",
    'Jersey'                    :   "United Kingdom",
    'Svalbard'                  :   "Norway",
    'Macau'                     :   "China",
    'Montserrat'                :   "United Kingdom",
    'Falkland Islnds'           :   "United Kingdom",
    'Norfolk Island'            :   "Australia",
    'Samoa America'             :   "United States of America",
    'Guadeloupe'                :   "France",
    'N.Mariana Islnd'           :   "United States of America",
    'Saint Barthélem'           :   "France",
    'Saint Martin'              :   "France",
    'Amer.Virgin Is.'           :   "United States of America",
    'Sint Maarten'              :   "Netherlands",
    'Christmas Islnd'           :   "Australia",
    'Aland Islands'             :   "Finland",
    'Saint Helena'              :   'United Kingdom',
    'Minor Outl.Isl.'           :   'United States of America',
    'Palestine'                 :   'Palestinian Territories'
}